title : Chao's Blog
author: chao
email: 543164029@qq.com
description: > # this means to ignore newlines until "baseurl:"
  nothing
# social links
# twitter_username: your-twitter-handle
github_username:  https://github.com/chao5512

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
